
package com.epam.jmp.webservice.model.task1;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tickets", targetNamespace = "http://task1.model.webservice.jmp.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tickets {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookTicket", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.BookTicket")
    @ResponseWrapper(localName = "bookTicketResponse", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.BookTicketResponse")
    @Action(input = "http://task1.model.webservice.jmp.epam.com/tickets/bookTicketRequest", output = "http://task1.model.webservice.jmp.epam.com/tickets/bookTicketResponse")
    public BigDecimal bookTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.jmp.webservice.model.task1.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.GetTicket")
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.GetTicketResponse")
    @Action(input = "http://task1.model.webservice.jmp.epam.com/tickets/getTicketRequest", output = "http://task1.model.webservice.jmp.epam.com/tickets/getTicketResponse")
    public Ticket getTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "refund", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.Refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.RefundResponse")
    @Action(input = "http://task1.model.webservice.jmp.epam.com/tickets/refundRequest", output = "http://task1.model.webservice.jmp.epam.com/tickets/refundResponse")
    public void refund(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "payBookedTicked", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.PayBookedTicked")
    @ResponseWrapper(localName = "payBookedTickedResponse", targetNamespace = "http://task1.model.webservice.jmp.epam.com/", className = "com.epam.jmp.webservice.model.task1.PayBookedTickedResponse")
    @Action(input = "http://task1.model.webservice.jmp.epam.com/tickets/payBookedTickedRequest", output = "http://task1.model.webservice.jmp.epam.com/tickets/payBookedTickedResponse")
    public void payBookedTicked(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

}
